language: ruby
cache: bundler
rvm:
  - 2.1

branches:
  only:
    - gh-pages

install: gem install bundler && bundle install

script: jekyll build -i && htmlproof ./_site

after_success: s3_website push