language: ruby
cache: bundler
rvm:
  - 2.1
branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_68227d46cd32_key -iv $encrypted_68227d46cd32_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  # 改变文件权限
  - chmod 600 ~/.ssh/id_rsa
  # 配置 ssh
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  # 配置 git 信息
  - git config --global user.name 'Travis CI'
  - git config --global user.email travis@jimmylv.com
  # 配置 qshell
  - wget http://devtools.qiniu.com/qshell-v2.0.5.zip
  - sudo apt-get install unzip
  - unzip qshell-*.zip
  - ./qshell_linux_amd64 account $QiNiuAK $QiNiuSK
install:
  - gem install bundler
  - bundle install
script:
  - jekyll build
  - ./qshell_linux_amd64 qupload scripts/qiniu.conf.json
after_success:
  # - s3_website push
  - |
    cd _site
    touch .nojekyll
    git status
    git init
    git add .
    git commit -m "Deploy at `date +"%Y-%m-%d %H:%M"`"
    # Make sure to make the output quiet, or else the API token will leak!
    git push -f -q git@git.coding.net:jimmylv/note-blog.git master:master > /dev/null 2>&1
